<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreCustomerMessageRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|max:200',
            'email' => 'required|max:200|email',
            'message' => 'required',
        ];
    }
    public function messages()
    {
        return [
            'name.required' => 'Tên không được bỏ trống',
            'name.max' => 'Tên không được quá 200 ký tự',
            'email.required' => 'Email không được bỏ trống',
            'email.max' => 'Email không được quá 200 ký tự',
            'email.email' => 'Giá trị bạn vừa nhập không phải email',
            'message.required' => 'Lời nhắn không được bỏ trống',
        ]; // TODO: Change the autogenerated stub
    }
}
