<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreRoleRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|max:200|unique:roles,name,'.$this->id,
            'display_name' => 'required|max:200',
            'description' => 'required'
        ];
    }

    public function messages()
    {
        return [
            'name.required' => 'Tên vai trò không được bỏ trống',
            'name.max' => 'Tên vai trò quá dài',
            'name.unique' => 'Tên danh mục đã tồn tại',
            'display_name.required' => 'Tên hiển thị không được bỏ trống',
            'display_name.max' => 'Tên hiển thị quá dài',
            'description.required' => 'Mô tả không được bỏ trống'
        ]; // TODO: Change the autogenerated stub
    }
}
